### ISSUE TITLE
Link nav buttons in persistent footer ( data info)

### ISSUE THREAD

**Issue by allthesignals** [allthesignals/cityxcity#137]
Footer links: "About", "Data Info", "Legal", "Export". "Legal" is a separate page. "Export" only shows on district view. Excepting "Legal" and "Export," the other links position browser scroll location to their section on the splash page.

**Comment by arouault** [comment]
What is your question @allthesignals

**Comment by allthesignals** [comment]
@arouault I think this question was answered during the last meeting.

**Comment by arouault** [comment]
Great!
