### ISSUE TITLE
Button to export complete dataset in csv, preferably by filter state. Functional Export Button / pop up

### ISSUE THREAD

**Issue by allthesignals** [allthesignals/cityxcity#142]

**Comment by arouault** [comment]
Please implement pop up part

**Comment by allthesignals** [comment]
Currently, it looks like this, but does not export map yet: @arouault 
![Screen Shot 2017-06-18 at 2.59.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455fb6b7191a37af117224f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ee5d26d0a77923540a5bb854ab600b9208b4bd1e5b98b4dd2f42f67b6d5db1063474f4dcbed5727a29f41c95cff4ce94c57a1173562e7762431.png)

**Comment by allthesignals** [comment]
![Screen Shot 2017-06-18 at 3.02.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455fb6b7191a37bf112294f5b565ecc3c4a4356bcbbd671f3e57862804e0ee5d26d0a77923540a5bb854ab600b9208b4bd1e5b98b4dd2f42f67b6d5db1063474f4dcbed5727a39b41c95cff4ce94c57a11a3361e6762431.png)
