### ISSUE TITLE
Update icon symbology and logic to reflect associating places with investments

### ISSUE THREAD

**Issue by allthesignals** [allthesignals/cityxcity#144]
Only places are plotted. All investments must be related to a place.

**Comment by allthesignals** [comment]
![Screen Shot 2017-06-18 at 4.37.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455fb6b7191a37cf1112c4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5d26d0a77923540a5bb854ab600b9208b4bd1e5b98b4dd2f42f67b6d5db1063474f4dcbed5727a39b41c95cff4ce94c5da61b3763ee762431.png)

**Comment by arouault** [comment]
What's the question @allthesignals

**Comment by allthesignals** [comment]
@arouault sorry, I wrote it in the Google Sheets, here it is:
```
Alright, I'm understanding more, but I still have questions about clustering: it looks like the cluster icon (which is normally for investments) is still in the design for the new icon logic. It's confusing because I'm not sure what's supposed to cluster and what doesn't cluster. If the investments cluster, then when they de-cluster, what happens? They're not being mapped because they only show up when associated with a place. So do places cluster? And if they do, do they use the cluster badge design? +monani@utiledesign.com lemme know - thanks.
```

**Comment by allthesignals** [comment]
Nupoor wrote: combined place/investment icons cluster together. However the idea was to count only number of investments. For example, if there were two place icons with two investments each, when they cluster the number on the badge would be 4 (sum of two and two investments)

**Comment by arouault** [comment]
@allthesignals What is the status of this issue?

**Comment by allthesignals** [comment]
@arouault the logic isn't right just yet, it doesn't cluster correctly but I understand now.
