### ISSUE TITLE
Reconcile names of place types and subtypes with data structure

### ISSUE THREAD

**Issue by allthesignals** [allthesignals/cityxcity#150]

**Comment by arouault** [comment]
Change labels of place types in panel and map to be consistent with data structure, specifically: culture and entertainment becomes "Arts and Culture", Government should be  "Civic Institution", Food should be "Food Sales", Business should be "Office", "Collision Point" should be "Community Hub", ADD IN NEW PLACE TYPE called "Mixed Use Development" and use the placeholder icon for this

**Comment by allthesignals** [comment]
None of the test data will work anymore now because these labels are different
