### ISSUE TITLE
Fix district cards on splash page

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#187]
Images are not displaying for each district on splash page.  All cards should have an image similar to Peabody

![image](https://user-images.githubusercontent.com/19911108/37246983-7de562aa-2481-11e8-865f-aa2ca9c21073.png)

**Comment by allthesignals** [comment]
In my local version, this is only true for New Bedford. @laurabarrett can you please re-upload the image for New Bedford? I would use a PNG type file (file extension is .png) instead of JPG.

**Comment by nupoormonani** [comment]
@allthesignals I am not able to see images for any district other than Pabody on the splash page at my end. Why does it vary from user to user? And how can we resolve it? See attached, this is what my splash page looks like. 

![image](https://user-images.githubusercontent.com/19911108/37974565-3bd84c88-31ab-11e8-8666-bd19e5836d56.png)

**Comment by nupoormonani** [comment]
OK, cc-ing @laurabarrett as a reminder.

**Comment by ericyoungberg** [comment]
Hmm, I'm not seeing it showing up. I've refreshed a view times and cleared my cache but it still looks missing on my end. 

![capture d ecran 2018-05-08 a 1 41 21 pm](https://user-images.githubusercontent.com/6749126/39773317-ac759c08-52c5-11e8-8282-a7cf8e3bc14c.png)

Would you mind sending me an email with the image attached? I'll try figuring out why Fieldbook is giving us trouble.

**Comment by laurabarrett** [comment]
weird! it shows in mine. i'll reupload. sorry about that!
![nb fieldbook](https://user-images.githubusercontent.com/29575235/39773667-c6cfff20-52c6-11e8-8aec-8adaeff539c9.JPG)

**Comment by laurabarrett** [comment]
Is it OK now?

**Comment by ericyoungberg** [comment]
Perfect! 👍
