### ISSUE TITLE
Replace text in "About" section

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#188]
Replace Latin text in the "about Block x Block", "About TDI", and "About MassDevelopment" sections on homepage with this text:

https://docs.google.com/document/d/1kBb9QxqNEsMQ-Nw_Komvg1jL2uGxJaK9Il9krPnwuns/edit

**Comment by allthesignals** [comment]
@nupoormonani the file for that can be found here:

https://github.com/allthesignals/cityxcity/blob/develop/app/templates/index.hbs#L35

If you click the pencil icon in the top right, you can edit the file directly. It's just HTML at that point.

**Comment by nupoormonani** [comment]
@allthesignals cc @laurabarrett I have updated the text base don the attached doc from Laura dated 9/15/17. How can I check if its displaying correctly?

[About Block x Block and Data Info.pdf](https://github.com/allthesignals/cityxcity/files/1852399/About.Block.x.Block.and.Data.Info.pdf)

**Comment by laurabarrett** [comment]
@nupoormonani cc @allthesignals  going into the link for editing in matt's post it looks like the text is still lorem ipsum. is it possible the edit just didnt save?

**Comment by nupoormonani** [comment]
@laurabarrett Just noticed that, too. I went in and made the changes again and generated a "pull request" Think this needs approval by @allthesignals to appear on the page. See attached screenshot.

![image](https://user-images.githubusercontent.com/19911108/38560231-2474dd06-3ca3-11e8-9415-d6a4bcced618.png)

**Comment by allthesignals** [comment]
Just merged! Thanks.
