### ISSUE TITLE
Restore clustering function

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#190]
Restore clustering function for point icons. This screenshot is from Haverhill:

![image](https://user-images.githubusercontent.com/19911108/37247038-f0e78e4e-2482-11e8-93cd-c45a1453cddb.png)

Should look like this: 

![image](https://user-images.githubusercontent.com/19911108/37247042-0c142f74-2483-11e8-8807-cc81a013dd30.png)

**Comment by ericyoungberg** [comment]
The above commit isn't related to this issue and should be ignored in this context. I meant to close #195.
