### ISSUE TITLE
Display Google Street View on investment place and cards where photo not available

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#195]
Currently looks like:
![image](https://user-images.githubusercontent.com/19911108/37247209-eeea9a66-2485-11e8-9153-9b8a6e656ba3.png)

**Comment by allthesignals** [comment]
@nupoormonani Hmmm - the missing image may be related to something else. 

I think that is a Place, but something is wrong with the image either from the database or from Google. The default should always be streetview. If you can help me find that particular example, I can look into it, but currently the app displays streetview by default.

**Comment by allthesignals** [comment]
Also, investments (which use the badges in your screenshot) don't show street view. Are you sure you want to show street view for the investments by default? Investments are a little more conceptual and don't necessary have a single location - they also get their location information from their associated places.

**Comment by nupoormonani** [comment]
@allthesignals the place cards seem to be displaying street view images correctly now. I'll let you know if I spot this issue again. Re. images for investments, yes they are more conceptual compared to places and ideally should display specific user-uploaded images. But we will likely not have these for the MVP. So, as let's have the investment cards display a Google street view of the place it is associated with.

**Comment by ericyoungberg** [comment]
Closed by https://github.com/allthesignals/cityxcity/commit/fd82675065ead678bd93e9866d78caaac7e30fc1
