### ISSUE TITLE
Display place name in hover-over box

### ISSUE THREAD

**Issue by nupoormonani** [allthesignals/cityxcity#196]
Place name appears in hover-over boxes but not all. It should appear here: 
![image](https://user-images.githubusercontent.com/19911108/37247257-628ef14c-2486-11e8-9a24-2d2309bb194c.png)

Use field "name"

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/37259276-a84c3dd2-255a-11e8-9040-03eece78021d.png)

This is done
