### ISSUE TITLE
Investment change over time

### ISSUE THREAD

**Issue by johnmccartin** [allthesignals/cityxcity#36]
Investments need to be displayed differently depending on its having one of four statuses:
- Proposed
- In Progress
- Closed
- Failed

Display needs to to change over time depending on the request date/quarter.

NB: Closed is used here in the financial sense (something fellows should be accustomed to), and is totally distinct from a features "closing date." I find this confusing, resolution tbd.

Proposed and In Progress investments are visible but less visually important (smaller or more transparent).

Closed investments are visible, visually important, and are shown this way from close date/quarter forward.

Failed investments are not visible. (John to check with Laura to make sure this is true.)

**Comment by allthesignals** [comment]
Thanks, @johnmccartin. Have you thought about how the data should be stored? Can you help me understand how this fits into the sparkline/histogram graph (with the time stylus)? Does that component shows a count of features by some set or specified time intervals? 

"Display needs to to change over time depending on the request date/quarter" -> I'm not sure what this means exactly, but I sort of get it.

How do the specific attributes (which we're tracking changes) relate to this? Maybe if you could think about how this kind of graph would be made in Excel (excepting the time part), I could understand better. I could see the sparkline/histogram graph having time interval "bins" that are clickable.

**Comment by johnmccartin** [comment]
Closing based on change in spec and how we're doing it technically
