### ISSUE TITLE
User sees "completed" investments by default

### ISSUE THREAD

**Issue by johnmccartin** [allthesignals/cityxcity#58]
When arriving at the map view, user sees investments filtered by investment_status == "completed"

**Comment by johnmccartin** [comment]
Features and parcels not shown by default

**Comment by allthesignals** [comment]
See https://docs.google.com/spreadsheets/d/1AZ3ilO3_Hx9gHW4T428a9Wxt-3kQWHiSjKQR1xsDfE0/edit#gid=1818022600 for completed data structure
