### ISSUE TITLE
User can see district-wide call-to-action on screen at all times

### ISSUE THREAD

**Issue by johnmccartin** [allthesignals/cityxcity#62]
District-wide call-to-action text is set dynamically for each city by admin user.

**Comment by allthesignals** [comment]
@johnmccartin where would this go in the mockup? Thanks!

**Comment by johnmccartin** [comment]
So, this should either live at the top next to the login/logout, or on a bar running along the bottom (which would otherwise hold links to About, Credits, Legal, etc.

My hunch is that it should go up top, since the bottom bar is more subtle and for less important info. ...but if it's getting crowded at the top, we can try it at the bottom.

Thanks!

**Comment by allthesignals** [comment]
@johnmccartin to send wireframes for this, waiting for that before moving ahead.
